name: Build
permissions:
  contents: write # access to check out code and install dependencies
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: update apt
        run: sudo apt-get update -y

      - name: install dependencies
        run: sudo apt-get install -y build-essential clang pkg-config libjpeg-dev libpng-dev

      - name: Cache ImageMagick build
        uses: actions/cache@v4
        id: imagemagick-build-cache
        with:
          path: ImageMagick-7.1.1-29
          key: ${{ runner.os }}-imagemagick-7.1.1-29-build

      - name: configure imagemagick
        run: |
          echo "Building ImageMagick 7 from source..."
          wget https://github.com/ImageMagick/ImageMagick/archive/7.1.1-29.tar.gz
          tar xzf 7.1.1-29.tar.gz
          cd ImageMagick-7.1.1-29

          # Configure and build ImageMagick 7
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --disable-static \
            --with-modules \
            --with-quantum-depth=16 \
            --without-perl

          make -j$(nproc)
          cd ..

      - name: Build and install imagemagick
        run: |
          cd ImageMagick-7.1.1-29
          sudo make install
          cd ..

      - name: build
        run: . "$HOME/.cargo/env" && cargo build --release

      - name: Create release assets
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          BUILD_DATE=$(date -u +"%Y-%m-%d")

          # Create checksums
          sha256sum target/release/rocksonic-rs > checksums.txt

          # Create release notes
          cat > release-notes.md << EOF
          # Latest Build - $BUILD_DATE

          **Commit:** [\`$SHORT_SHA\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})

          ## Download
          - **Linux AMD64**: \`rocksonic-rs\`

          ## Installation
          1. Download the binary
          2. Make it executable: \`chmod +x rocksonic-rs\`
          3. Run it: \`./rocksonic-rs\`

          ## Requirements
          - This binary requires ImageMagick 7 and ffmpeg to be installed on the target system
          - On Ubuntu/Debian: \`sudo apt install imagemagick ffmpeg\`

          ## Build Information
          - **Built on:** $BUILD_DATE
          - **Go Version:** $(cargo --version)
          - **ImageMagick Version:** $(magick -version | head -1)
          - **Git SHA:** ${{ github.sha }}
          - **Binary Size:** $(du -h ./target/release/rocksonic-rs | cut -f1)

          ## Verification
          Verify file integrity using SHA256:
          \`\`\`bash
          sha256sum -c checksums.txt
          \`\`\`
          EOF

      - name: Delete previous latest release
        run: |
          # Delete the previous "latest" release and tag if they exist
          gh release delete latest --yes || echo "No previous 'latest' release found"
          git push --delete origin latest || echo "No previous 'latest' tag found"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest release
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          BUILD_DATE=$(date -u +"%Y-%m-%d")

          git tag latest
          git push origin latest

          gh release create latest \
            --title "Latest Build" \
            --notes "Built from commit $SHORT_SHA on $BUILD_DATE" \
            --latest \
            target/release/rocksonic-rs \
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
